### ISSUE TITLE
Mention need to escape SMTP password in documentation

### ISSUE THREAD

**Issue by matthias-schuchardt** [exceptionless/Website#28]
When self-hosting Exceptionless, one needs to use [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) the SMTP-password. Since this is not obvious at the first glance, would you mind adding a short note to the [setup documentation](https://exceptionless.com/docs/self-hosting/docker/#simple-setup-wssl-support-and-smtp) hosted [here](https://github.com/exceptionless/Website/blob/master/content/docs/self-hosting/docker.md)? This might save your users a few hours and you guys a [few tickets](https://github.com/exceptionless/Exceptionless/issues/820).

**Comment by matthias-schuchardt** [comment]
Closed by this [pull request](https://github.com/exceptionless/Website/pull/29).

**Comment by niemyjski** [comment]
Thanks for the PR
