### ISSUE TITLE
Spaces in field names not escaped as documented

### ISSUE THREAD

**Issue by matthias-schuchardt** [exceptionless/Website#40]
The documentation on filtering & searching states that [spaces in field names of extended data are escaped with a `-`](https://exceptionless.com/docs/filtering-and-searching/#custom-extended-data).

To filter for such a field, the space however needs to be removed completely instead of being replaced with a dash. Furthermore, both field name and value are case-insensitive.

To filter for e.g. `Machine Name`, one would have to enter `data.MachineName:my-server123` or `data.mAcHiNeNaMe:My-SeRvEr123`.

I would therefore suggest to update the documentation as follows.

~~_NOTE: Field names will be lowercased and escaped. If your field contains a space it will be escaped with a -._~~
_NOTE: When filtering, remove spaces from field names (e.g. `data.MyField:18` instead of `data.My Field:18`)._

**Comment by niemyjski** [comment]
Thanks for pointing this out, I've dug through the code and updated the documentation. 

It now reads:

> All simple data types (`string`, `boolean`, `date`, `number`) that are stored in extended data will be indexed. _NOTE: Field names will be lowercased and escaped. Any field name that is not a valid identifier (containing only letter and digits) or is longer than 25 characters will be ignored.

**Comment by niemyjski** [comment]
Here is the code if you want to look at it: https://github.com/exceptionless/Exceptionless/blob/2d84a7703ecb630823b37f09598fb4ad6b190186/src/Exceptionless.Core/Extensions/PersistentEventExtensions.cs#L26-L27
